<?php

  /**
   * kirby-webpack helpers
   *
   * kirby-webpack needs this plugin to work.
   * Don't remove it!
   */

  // Use it to test if the site is called from the webpack dev server
  function isWebpack() {
    return !!(
      isset($_SERVER['HTTP_X_FORWARDED_FOR'])
      && $_SERVER['HTTP_X_FORWARDED_FOR'] == 'webpack'
    );
  }

  // Use it instead of css() for all your css files generated by webpack.
  // This will enable the livereload feature when your are in development
  function liveCSS ($href, $media = null) {
    return isWebpack() ? js($href) : css($href, $media);
  }
