<?php

  // globally available helpers function

  // Use it instead of css() for all your css files generated by webpack.
  // This will enable the live reloading feature when your are in development
  function liveCSS($href, $media = null) {
    return c::get('webpack', false) ? js($href) : css($href, $media);
  }